from typing import Protocol

from .schemas import (
    ArtifactContent,
    CreateRunCommand,
    Page,
    RepositorySummary,
    RunActionCommand,
    RunDetail,
    RunFilters,
    RunSummary,
    SystemHealth,
    WorkflowDetail,
    WorkflowSummary,
    WorkflowValidation,
)


class AgentAutoDevGateway(Protocol):
    def health(self) -> SystemHealth: ...
    def list_runs(self, filters: RunFilters) -> Page[RunSummary]: ...
    def get_run(self, run_id: str) -> RunDetail: ...
    def create_run(self, command: CreateRunCommand) -> RunDetail: ...
    def control_run(self, run_id: str, command: RunActionCommand) -> RunDetail: ...
    def list_workflows(self) -> list[WorkflowSummary]: ...
    def get_workflow(self, template_id: str) -> WorkflowDetail: ...
    def validate_workflow(self, source: str) -> WorkflowValidation: ...
    def list_repositories(self) -> list[RepositorySummary]: ...
    def read_artifact(self, run_id: str, artifact_id: str) -> ArtifactContent: ...
    def download_artifact(self, run_id: str, artifact_id: str) -> tuple[str, bytes]: ...
