import { act, render, screen, waitFor, cleanup } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { ApiProvider } from '../src/services/api';
import { LocaleProvider } from '../src/locales';
import { CreateTask } from '../src/components/CreateTask';
import { RunControls } from '../src/components/RunControls';
import { Tasks } from '../src/pages/Tasks';
import type { RunDetail } from '../src/typings/api';
import type { ReactNode } from 'react';
const template = { templateId: 'document.yaml', name: 'document', version: '1', description: '文档', stageCount: 1, jobCount: 1, valid: true };
function mount(children: ReactNode, path = '/tasks') { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return { client, ...render(<LocaleProvider><QueryClientProvider client={client}><ApiProvider token="test"><MemoryRouter initialEntries={[path]}>{children}</MemoryRouter></ApiProvider></QueryClientProvider></LocaleProvider>) }; }
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
function fakeFetch(post: () => Promise<unknown> = async () => ({ ok: false, status: 409, json: async () => ({ error: { code: 'CONCURRENCY_CONFLICT', message: '租约冲突', requestId: 'test' } }) })) { const fetch = vi.fn(async (path: string, options?: RequestInit) => { if (options?.method === 'POST') return post(); return { ok: true, json: async () => path.includes('/workflows') ? [template] : path.includes('/repositories') ? [] : { items: [], page: 1, pageSize: 20, total: 0 } }; }); vi.stubGlobal('fetch', fetch); return fetch; }
describe('创建与控制交互', () => {
  it('创建校验、失败保留表单与防重复', async () => { let resolve: (v: unknown) => void = () => {}; const fetch = fakeFetch(() => new Promise(r => { resolve = r; })); mount(<CreateTask open onClose={() => {}}/>); const user = userEvent.setup(); await waitFor(() => expect(screen.getByRole('button', { name: '创建并入队' })).toBeEnabled()); await user.click(screen.getByText('创建并入队')); expect(await screen.findByText('请填写任务需求')).toBeVisible(); await user.type(screen.getByPlaceholderText(/例如/), '补充文档'); await user.click(screen.getByRole('combobox', { name: '工作流模板' })); await user.click(await screen.findByText('document · v1 (document.yaml)')); await user.click(screen.getByText('创建并入队')); expect(screen.getByRole('button', { name: /创建并入队/ })).toBeDisabled(); expect(fetch.mock.calls.filter(c => c[1]?.method === 'POST')).toHaveLength(1); await act(async () => resolve({ ok: false, status: 409, json: async () => ({ error: { code: 'CONCURRENCY_CONFLICT', message: '租约冲突', requestId: 'test' } }) })); await waitFor(() => expect(screen.getByText(/CONCURRENCY_CONFLICT/)).toBeVisible()); expect(screen.getByPlaceholderText(/例如/)).toHaveValue('补充文档'); });
  it('成功跳转详情', async () => { fakeFetch(async () => ({ ok: true, json: async () => ({ run: { runId: 'new-run' } }) })); mount(<Routes><Route path="/tasks" element={<CreateTask open onClose={() => {}}/>}/><Route path="/tasks/new-run" element={<div data-testid="created-detail"/>}/></Routes>); const user = userEvent.setup(); await user.type(screen.getByPlaceholderText(/例如/), '新任务'); await user.click(screen.getByRole('combobox', { name: '工作流模板' })); await user.click(await screen.findByText('document · v1 (document.yaml)')); await user.click(screen.getByText('创建并入队')); expect(await screen.findByTestId('created-detail')).toBeInTheDocument(); });
  it('API allowedActions 限制控制，取消必须确认', async () => { const fetch = fakeFetch(); const detail = { run: { runId: 'test' }, allowedActions: ['cancel'], conversation: { available: false } } as RunDetail; mount(<RunControls detail={detail}/>); expect(screen.queryByText('恢复')).not.toBeInTheDocument(); const user = userEvent.setup(); await user.click(screen.getByText('取消任务')); expect(fetch).not.toHaveBeenCalled(); await user.click(screen.getByText('确认取消')); await waitFor(() => expect(screen.getByText(/CONCURRENCY_CONFLICT/)).toBeVisible()); });
  it('空数据与 URL 筛选区别', async () => { const fetch = fakeFetch(); mount(<Tasks/>, '/tasks?status=FAILED&query=missing&page=2'); expect(await screen.findByText('没有匹配的任务')).toBeVisible(); expect(fetch).toHaveBeenCalledWith(expect.stringContaining('status=FAILED'), expect.anything()); const user = userEvent.setup(); await user.click(screen.getByText('清除筛选')); await waitFor(() => expect(screen.getByText('还没有任务')).toBeVisible()); });
});
