import type { MessageKey } from './zh-CN';
export const enUS: Record<MessageKey, string> = {
  executionFinished: 'Execution finished', outputLimitHint: 'Only the saved output excerpt is available, up to 2048 characters per stream. See artifacts for the full task result.', rawOutput: 'Raw output excerpt', sessionPreparing: 'Session preparation', sessionHookResult: 'Preparation event returned', sessionStarted: 'Session initialization', modelReply: 'Model reply', toolInvocation: 'Tool call', modelResult: 'Model result', noReadableReply: 'This excerpt contains no model text reply. Check artifacts or the raw records.', incompleteOutput: 'Some records could not be fully parsed. Their content is preserved in the raw excerpt.',
  product: 'Auto Dev', subtitle: 'Development console', workspace: 'Intranet workspace', tasks: 'Tasks', workflows: 'Workflows', repositories: 'Repositories', system: 'System status',
  all: 'All', QUEUED: 'Queued', RUNNING: 'Running', WAITING: 'Waiting', PAUSED: 'Paused', SUCCEEDED: 'Succeeded', FAILED: 'Failed', CANCELLED: 'Cancelled', BLOCKED: 'Blocked', SKIPPED: 'Skipped',
  taskDescription: 'Create, monitor and control development tasks', refresh: 'Refresh', createTask: 'New task', updated: 'Last updated', searchTasks: 'Search title, run ID or workflow', status: 'Status', title: 'Task title', workflow: 'Workflow', node: 'Current node', repository: 'Repository', engine: 'Engine', createdAt: 'Created', duration: 'Duration', actions: 'Actions', detail: 'View details', noRepository: 'No repository', singleRepository: 'Single repository', pending: 'Not started', unknown: 'Unknown',
  noTasks: 'No tasks yet', noTasksDescription: 'Select a workflow and describe your first development task.', noResults: 'No matching tasks', noResultsDescription: 'Try a different status or search term.', clearFilters: 'Clear filters', loading: 'Reading run records…', failedLoad: 'Could not load data', unavailable: 'Service unavailable', unavailableDescription: 'Upstream state could not be read. Check the configuration and connection, then retry.', retryLoad: 'Reload', staleData: 'Refresh failed. Showing the last successfully loaded data.', total: 'Total', records: 'tasks', pagination: 'Pagination',
  task: 'Task requirements', taskHint: 'Describe the expected result and acceptance criteria. The task will be queued.', taskPlaceholder: 'For example: Add API documentation and tests, including recovery procedures.', requiredTask: 'Enter task requirements', requiredWorkflow: 'Select a workflow template', template: 'Workflow template', chooseTemplate: 'Select a configured template', optionalRepository: 'Repository (optional)', repositoryHint: 'Without a repository, a separate managed workspace will be used.', stages: 'Stages', jobs: 'Jobs', version: 'Version', cancel: 'Cancel', createAndQueue: 'Create and queue', submitting: 'Submitting',
  accessTitle: 'Access the console', accessDescription: 'Enter the access token provided by your administrator. It stays in this page’s memory only.', accessToken: 'Access token', tokenRequired: 'Enter an access token', connect: 'Verify and connect', signOut: 'Disconnect', language: 'Switch language', menu: 'Open navigation', close: 'Close',
  pause: 'Pause', resume: 'Resume', retry: 'Retry', skip: 'Skip', cancelRun: 'Cancel task', cancelTitle: 'Cancel this task?', cancelDescription: 'The executor handles cancellation at a safe boundary. Upstream concurrency checks still apply.', confirmCancel: 'Confirm cancellation', actionTitle: 'Task control', mode: 'Recovery mode', revise: 'Revise and execute', continueConversation: 'Continue conversation', feedback: 'Operator feedback', feedbackPlaceholder: 'Add instructions or requested changes (optional)', actionFailed: 'Action failed', conflict: 'Task state or lease has changed. Refresh and retry.', requestId: 'Request ID',
  back: 'Back to tasks', runId: 'Run ID', execution: 'Execution', artifacts: 'Artifacts', runInfo: 'Run information', events: 'Events', logs: 'Output summary', stdout: 'Standard output', stderr: 'Standard error', noOutput: 'No persisted output for this job yet.', attempt: 'Attempt', round: 'Round', session: 'Session', hasSession: 'Present', noSession: 'Not recorded', model: 'Model', start: 'Started', finish: 'Finished', errorCode: 'Error code', errorSummary: 'Error summary', noAttempts: 'No execution attempts yet', waitForDaemon: 'Task queued, awaiting the scheduler.', selectAttempt: 'Select a job to inspect execution', branch: 'Branch', managedWorkspace: 'Managed workspace', revision: 'State revision', taskBody: 'Requirements', pausePoint: 'Pause point', feedbackHistory: 'Feedback history', operations: 'External operations', debugContext: 'Redacted context', noEvents: 'No domain events yet', noArtifacts: 'No artifacts yet', noArtifactsDescription: 'Artifacts appear after jobs finish and pass validation.', preview: 'Preview', download: 'Download', fileType: 'Type', fileSize: 'Size', digest: 'SHA-256', gitRevision: 'Git revision', binary: 'Download only', artifactTooLarge: 'This artifact exceeds the preview limit. Try downloading it.', artifactGroup: 'Stage / attempt', noGraph: 'Frozen workflow definition unavailable', definitionWarning: 'Some historical fields are unavailable. Check run information.',
  workflowDescription: 'Inspect server templates and execution structure', searchWorkflows: 'Search template name or description', validateYaml: 'Validate YAML', valid: 'Valid', invalid: 'Invalid', templateId: 'Template ID', description: 'Description', modifiedAt: 'Updated', noWorkflows: 'No workflow templates configured', noWorkflowsDescription: 'Add YAML templates directly to the upstream workflow directory.', source: 'Read-only source', structure: 'Execution structure', workflowBack: 'Back to workflows', yamlSource: 'YAML source', yamlHint: 'Up to 1 MiB. Validation does not execute tasks or overwrite server templates.', uploadYaml: 'Upload YAML', validate: 'Validate strictly', validationPassed: 'Validation passed', validationFailed: 'Validation failed', yamlTooLarge: 'File exceeds 1 MiB', yamlFileType: 'Select a YAML file', yamlRequired: 'Paste or upload YAML',
  repositoryDescription: 'Configured repositories and integration capabilities', provider: 'Provider', project: 'Project', remote: 'Remote URL', baseBranch: 'Base branch', pipeline: 'Pipeline', enabled: 'Enabled', disabled: 'Disabled', capability: 'Capability', configured: 'Configured', offline: 'Offline adapter', noRepositories: 'No repositories configured', noRepositoriesDescription: 'Tasks without a repository remain available. Manage repository configuration upstream.', readonly: 'Read-only configuration',
  systemDescription: 'Service connection, scheduler and execution capabilities', bff: 'Console service', upstream: 'Execution engine', connected: 'Connected', disconnected: 'Unavailable', database: 'State store', stateDirectory: 'State directory', reachable: 'Reachable', unreachable: 'Unreachable', daemon: 'Scheduler', daemonStopped: 'Stopped', daemonStale: 'Stale process record', lastHeartbeat: 'Latest lease heartbeat', authState: 'Executor authentication', notProbed: 'Not probed', diagnostics: 'Diagnostics', availableAgents: 'Registered agents', availableTools: 'Registered tools', healthy: 'Connected', daemonDescription: 'When the scheduler is stopped, new tasks remain queued.', testEnvironment: 'Deterministic test environment', navigation: 'Main navigation', noData: 'No data', copy: 'Copy', apiError: 'Request failed', notFound: 'Page not found', home: 'Go to tasks',
};
