export const zhCN = {
  product: 'Auto Dev', subtitle: '研发任务控制台', workspace: '内网工作区', tasks: '任务中心', workflows: '工作流模板', repositories: '仓库配置', system: '系统状态',
  all: '全部', QUEUED: '排队中', RUNNING: '运行中', WAITING: '等待中', PAUSED: '已暂停', SUCCEEDED: '已完成', FAILED: '失败', CANCELLED: '已取消', BLOCKED: '已阻塞', SKIPPED: '已跳过',
  taskDescription: '创建、监控与控制研发任务', refresh: '刷新', createTask: '新建任务', updated: '最后更新', searchTasks: '搜索任务标题、运行 ID 或工作流',
  status: '状态', title: '任务标题', workflow: '工作流', node: '当前节点', repository: '仓库', engine: '执行引擎', createdAt: '创建时间', duration: '耗时', actions: '操作', detail: '查看详情', noRepository: '无仓任务', singleRepository: '单仓任务', pending: '尚未开始', unknown: '未知',
  noTasks: '还没有任务', noTasksDescription: '选择工作流并填写需求，创建你的第一个研发任务。', noResults: '没有匹配的任务', noResultsDescription: '尝试调整状态或搜索关键词。', clearFilters: '清除筛选', loading: '正在读取运行记录…', failedLoad: '读取失败', unavailable: '服务不可用', unavailableDescription: '无法读取上游运行状态。请检查配置与服务连接后重试。', retryLoad: '重新加载', staleData: '刷新失败，当前显示最近一次成功读取的数据。', total: '总计', records: '条任务', pagination: '分页',
  task: '任务需求', taskHint: '描述期望的结果与验收条件。任务创建后将进入队列。', taskPlaceholder: '例如：补充 API 文档和测试，包含异常恢复流程。', requiredTask: '请填写任务需求', requiredWorkflow: '请选择工作流模板', template: '工作流模板', chooseTemplate: '选择已配置的模板', optionalRepository: '关联仓库（可选）', repositoryHint: '不选择仓库时，将使用独立的受管工作区。', stages: '阶段', jobs: '节点', version: '版本', cancel: '取消', createAndQueue: '创建并入队', submitting: '正在提交',
  accessTitle: '访问控制台', accessDescription: '输入管理员提供的访问令牌。令牌仅保留在当前页面的内存中。', accessToken: '访问令牌', tokenRequired: '请输入访问令牌', connect: '验证并连接', signOut: '退出连接', language: '切换语言', menu: '打开导航', close: '关闭',
  pause: '暂停', resume: '恢复', retry: '重试', skip: '跳过', cancelRun: '取消任务', cancelTitle: '确认取消此任务？', cancelDescription: '执行器将在安全边界处理取消请求。此操作由上游进行并发校验。', confirmCancel: '确认取消', actionTitle: '任务控制', mode: '恢复方式', revise: '修订后执行', continueConversation: '继续原会话', feedback: '人工反馈', feedbackPlaceholder: '填写补充说明或修改要求（可选）', actionFailed: '操作失败', conflict: '任务状态或租约已变化，请刷新后重试。', requestId: '请求 ID',
  back: '返回任务中心', runId: '运行 ID', execution: '执行过程', artifacts: '产物', runInfo: '运行信息', events: '事件', logs: '输出摘要', stdout: '标准输出', stderr: '标准错误', noOutput: '此节点尚无持久化输出。', attempt: '尝试', round: '轮次', session: '会话', hasSession: '存在', noSession: '未记录', model: '模型', start: '开始时间', finish: '结束时间', errorCode: '错误码', errorSummary: '错误摘要', noAttempts: '尚无执行尝试', waitForDaemon: '任务已入队，等待调度器执行。', selectAttempt: '选择节点查看执行记录', branch: '分支', managedWorkspace: '受管工作区', revision: '状态版本', taskBody: '需求正文', pausePoint: '暂停点', feedbackHistory: '反馈历史', operations: '外部操作', debugContext: '脱敏上下文', noEvents: '暂无领域事件', noArtifacts: '尚无产物', noArtifactsDescription: '节点完成并通过校验后，产物会显示在这里。', preview: '预览', download: '下载', fileType: '类型', fileSize: '大小', digest: 'SHA-256', gitRevision: 'Git revision', binary: '此文件仅支持下载', artifactTooLarge: '此产物超出预览上限，可尝试下载。', artifactGroup: '阶段 / 尝试', noGraph: '冻结工作流定义不可用', definitionWarning: '部分历史字段不可用，请检查运行信息。',
  workflowDescription: '查看服务器模板与执行结构', searchWorkflows: '搜索模板名称或描述', validateYaml: '校验 YAML', valid: '有效', invalid: '无效', templateId: '模板 ID', description: '描述', modifiedAt: '更新时间', noWorkflows: '尚未配置工作流模板', noWorkflowsDescription: '请在上游配置目录添加直属 YAML 模板。', source: '只读源码', structure: '执行结构', workflowBack: '返回工作流模板', yamlSource: 'YAML 源码', yamlHint: '最多 1 MiB。校验不会执行任务或覆盖服务器模板。', uploadYaml: '上传 YAML', validate: '严格校验', validationPassed: '校验通过', validationFailed: '校验失败', yamlTooLarge: '文件超过 1 MiB', yamlFileType: '请选择 YAML 文件', yamlRequired: '请粘贴或上传 YAML',
  repositoryDescription: '查看上游配置中的仓库与能力', provider: '托管平台', project: '项目', remote: '远端地址', baseBranch: '基准分支', pipeline: '流水线', enabled: '已启用', disabled: '未启用', capability: '能力状态', configured: '已配置', offline: '离线适配器', noRepositories: '尚未配置仓库', noRepositoriesDescription: '无仓任务仍可正常创建。仓库配置由上游管理。', readonly: '只读配置',
  systemDescription: '服务连接、调度器与执行能力', bff: '管理端服务', upstream: '执行引擎', connected: '已连接', disconnected: '不可用', database: '状态存储', stateDirectory: '状态目录', reachable: '可达', unreachable: '不可达', daemon: '调度器', daemonStopped: '未运行', daemonStale: '进程记录失效', lastHeartbeat: '最近租约心跳', authState: '执行器认证', notProbed: '未探测', diagnostics: '诊断', availableAgents: '已注册 Agent', availableTools: '已注册 Tool', healthy: '连接正常', daemonDescription: '调度器未运行时，新建任务将保留在队列中。', testEnvironment: '确定性测试环境', navigation: '主导航', noData: '暂无数据', copy: '复制', apiError: '请求失败', notFound: '页面不存在', home: '前往任务中心',
} as const;
export type MessageKey = keyof typeof zhCN;
