import { useRef, useState } from 'react';
import { Alert, Button, Input, Tabs, Tag } from 'antd';
import { ArrowLeft, ChevronRight, RefreshCcw, Search, Upload, Yaml } from '@sofa-design/icons';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { useLocale } from '../locales';
import { useApi } from '../services/api';
import { dateTime } from '../services/time';
import { BusinessModal, EmptyState, ErrorNotice, ErrorState, IconButton, LoadingState, PageHeader, PageLayout, PagePanel, TextIconButton } from '../components/common';
import type { Graph } from '../typings/api';
import styles from './catalog.module.less';
export function WorkflowStructure({ graph }: { graph: Graph }) { const { t } = useLocale(); return <div className={styles.structure}>{graph.stages.map((s, index) => <section className={styles.stage} key={s.name}><h3 className={styles.stageName}><span className="muted mono">{String(index + 1).padStart(2, '0')} / </span>{s.name}</h3><div className={styles.jobs}>{s.jobs.map(j => <div className={styles.job} key={j.name}><strong>{j.name}</strong><p className="muted mono">{j.type === 'agent' ? j.agent : j.tool}</p>{j.model && <p className="muted">{j.model}</p>}</div>)}</div></section>)}{!graph.stages.length && <EmptyState title="noGraph"/>}<span className="muted">{graph.stages.length} {t('stages')} · {graph.stages.reduce((sum, s) => sum + s.jobs.length, 0)} {t('jobs')}</span></div>; }
export function ValidateYaml({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { t } = useLocale(); const api = useApi(); const [source, setSource] = useState(''); const [fileError, setFileError] = useState<string | null>(null); const input = useRef<HTMLInputElement>(null); const locked = useRef(false);
  const validate = useMutation({ mutationFn: () => api.validate(source) });
  const changeSource = (value: string) => { setSource(value); validate.reset(); setFileError(null); };
  const upload = async (file?: File) => { if (!file) return; if (!/\.ya?ml$/i.test(file.name)) { setFileError(t('yamlFileType')); return; } if (file.size > 1048576) { setFileError(t('yamlTooLarge')); return; } changeSource(await file.text()); };
  const submit = async () => { if (locked.current) return; if (!source.trim()) { setFileError(t('yamlRequired')); return; } if (new TextEncoder().encode(source).length > 1048576) { setFileError(t('yamlTooLarge')); return; } locked.current = true; try { await validate.mutateAsync(); } catch { /* 统一错误组件展示 */ } finally { locked.current = false; } };
  return <BusinessModal title={t('validateYaml')} open={open} onCancel={onClose} closable={!validate.isPending} footer={<><Button onClick={onClose} disabled={validate.isPending}>{t('close')}</Button><Button type="primary" loading={validate.isPending} onClick={() => void submit()}>{t('validate')}</Button></>}><div className="stack"><p className="muted">{t('yamlHint')}</p><label htmlFor="yaml-source">{t('yamlSource')}</label><Input.TextArea id="yaml-source" rows={10} value={source} disabled={validate.isPending} onChange={e => changeSource(e.target.value)} className="mono"/><div><TextIconButton icon={<Upload/>} onClick={() => input.current?.click()} disabled={validate.isPending}>{t('uploadYaml')}</TextIconButton><input type="file" accept=".yaml,.yml" hidden ref={input} onChange={e => void upload(e.target.files?.[0])}/></div>{fileError && <Alert type="error" message={fileError}/>} {validate.error && <ErrorNotice error={validate.error}/>} {validate.data?.valid && <Alert type="success" message={t('validationPassed')} description={`${validate.data.name} · v${validate.data.version}`}/>}</div></BusinessModal>;
}
export function Workflows() {
  const { t, locale } = useLocale(); const api = useApi(); const [query, setQuery] = useState(''); const [open, setOpen] = useState(false);
  const result = useQuery({ queryKey: ['workflows'], queryFn: ({ signal }) => api.workflows(signal) });
  const rows = result.data?.filter(w => `${w.name} ${w.templateId} ${w.description}`.toLowerCase().includes(query.toLowerCase())) ?? [];
  return <PageLayout><PageHeader title={t('workflows')} description={t('workflowDescription')} actions={<><IconButton label={t('refresh')} icon={<RefreshCcw/>} loading={result.isFetching} onClick={() => void result.refetch()}/><TextIconButton type="primary" icon={<Yaml/>} onClick={() => setOpen(true)}>{t('validateYaml')}</TextIconButton></>}/><PagePanel><div className={styles.toolbar}><Input prefix={<Search/>} aria-label={t('searchWorkflows')} placeholder={t('searchWorkflows')} value={query} onChange={e => setQuery(e.target.value)} allowClear/></div>{result.isPending ? <LoadingState/> : result.error ? <ErrorState error={result.error} retry={() => void result.refetch()}/> : !rows.length ? <EmptyState title={query ? 'noResults' : 'noWorkflows'} description={query ? 'noResultsDescription' : 'noWorkflowsDescription'}/> : <div className={styles.entries}>{rows.map(w => <article key={w.templateId} className={styles.workflow}><div><div className={styles.workflowHeading}><Link to={`/workflows/${encodeURIComponent(w.templateId)}`}>{w.name}</Link><span className={`${styles.id} mono`}>v{w.version}</span><Tag color={w.valid ? 'success' : 'error'}>{t(w.valid ? 'valid' : 'invalid')}</Tag></div><p className={styles.description}>{w.description}</p><div className={styles.meta}><span className="mono">{w.templateId}</span><span>{w.stageCount} {t('stages')} / {w.jobCount} {t('jobs')}</span><span>{t('modifiedAt')} {dateTime(w.updatedAt, locale)}</span></div></div><Link to={`/workflows/${encodeURIComponent(w.templateId)}`} aria-label={`${t('detail')} ${w.name}`}><ChevronRight width={18}/></Link></article>)}</div>}</PagePanel><ValidateYaml open={open} onClose={() => setOpen(false)}/></PageLayout>;
}
export function WorkflowDetailPage() {
  const { templateId = '' } = useParams(); const api = useApi(); const { t } = useLocale();
  const result = useQuery({ queryKey: ['workflow', templateId], queryFn: ({ signal }) => api.workflow(templateId, signal) });
  if (result.isPending) return <PageLayout><LoadingState/></PageLayout>;
  if (!result.data) return <PageLayout><ErrorState error={result.error ?? new Error(t('failedLoad'))} retry={() => void result.refetch()}/></PageLayout>;
  const w = result.data;
  return <PageLayout><Link to="/workflows" className={styles.back}><ArrowLeft width={14}/>{t('workflowBack')}</Link><PageHeader title={w.name} description={`${w.templateId} · v${w.version} · ${w.description}`} actions={<IconButton label={t('refresh')} icon={<RefreshCcw/>} onClick={() => void result.refetch()}/>}/><PagePanel><Tabs style={{ padding: '0 20px' }} items={[{ key: 'structure', label: t('structure'), children: <WorkflowStructure graph={w.graph}/> }, { key: 'source', label: t('source'), children: <pre className={styles.source}>{w.source}</pre> }]}/></PagePanel>{w.errors.map((e, i) => <Alert key={i} type="error" message={e.message}/>)}</PageLayout>;
}
